version: '3.9'

services:
  nginx:
    image: openresty/openresty:1.25.3.1-0-alpine
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    ports:
      - "8081:80"
    restart: unless-stopped

  proxima:
    build: .
    container_name: proxima-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
    environment:
      - DOCKER_CONTAINER=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: proxima-network