server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

logging:
  level:
    com.freesidenomad.proxima: DEBUG
    org.springframework.web: INFO

springdoc:
  api-docs:
    path: /proxima/api-docs
  swagger-ui:
    path: /proxima/api/docs
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true