server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

proxima:
  downstream:
    url: http://httpbin.org
  active-preset: admin_user
  presets:
    - name: admin_user
      display-name: "Admin User"
      headers:
        Authorization: "Bearer admin-jwt-token"
        X-User-Role: "admin"
        X-User-ID: "admin-001"
    - name: regular_user
      display-name: "Regular User"
      headers:
        Authorization: "Bearer user-jwt-token"
        X-User-Role: "user"
        X-User-ID: "user-001"
    - name: api_client
      display-name: "API Client"
      headers:
        Authorization: "Bearer api-client-token"
        X-Client-Type: "api"
        X-Rate-Limit: "1000"
  routes:
    - path-pattern: "/api/users/**"
      target-url: "http://localhost:8081"
      description: "User management service"
      enabled: true
    - path-pattern: "/api/invoices/**"
      target-url: "http://localhost:8082"
      description: "Invoice processing service"
      enabled: true
    - path-pattern: "/api/auth/**"
      target-url: "http://localhost:8083"
      description: "Authentication service"
      enabled: true

logging:
  level:
    com.freesidenomad.proxima: DEBUG
    org.springframework.web: INFO