proxima:
  downstream:
    url: ${PROXIMA_DOWNSTREAM_URL:http://httpbin:80}
  active-preset: ${PROXIMA_ACTIVE_PRESET:admin_user}
  presets:
    - name: admin_user
      display-name: "Admin User"
      headers:
        Authorization: ${PROXIMA_ADMIN_AUTH:Bearer admin-jwt-token}
        X-User-Role: "admin"
        X-User-ID: "admin-001"
        X-Forwarded-By: "Proxima-Proxy"
    - name: regular_user
      display-name: "Regular User"
      headers:
        Authorization: ${PROXIMA_USER_AUTH:Bearer user-jwt-token}
        X-User-Role: "user"
        X-User-ID: "user-001"
        X-Forwarded-By: "Proxima-Proxy"
    - name: api_client
      display-name: "API Client"
      headers:
        Authorization: ${PROXIMA_API_AUTH:Bearer api-client-token}
        X-Client-Type: "api"
        X-Rate-Limit: "1000"
        X-Forwarded-By: "Proxima-Proxy"
  routes:
    - path-pattern: "/api/users/**"
      target-url: ${PROXIMA_USERS_SERVICE_URL:http://localhost:8081}
      description: "User management service"
      enabled: ${PROXIMA_USERS_SERVICE_ENABLED:true}
    - path-pattern: "/api/invoices/**"
      target-url: ${PROXIMA_INVOICES_SERVICE_URL:http://localhost:8082}
      description: "Invoice processing service"
      enabled: ${PROXIMA_INVOICES_SERVICE_ENABLED:true}
    - path-pattern: "/api/auth/**"
      target-url: ${PROXIMA_AUTH_SERVICE_URL:http://localhost:8083}
      description: "Authentication service"
      enabled: ${PROXIMA_AUTH_SERVICE_ENABLED:true}

logging:
  level:
    com.freesidenomad.proxima: INFO
    org.springframework.web: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized